# wrangler.toml - Configuration for the Cloudflare Worker

# Top-level configuration
name = "gitshow" # Replace with your desired worker name
main = "gitshow_worker.js" # The entry point for your worker script
compatibility_date = "2024-03-20" # Use a recent compatibility date

# Optional: Add environment variables if needed (e.g., for API keys, though not used here)
# [vars]
# MY_VARIABLE = "value"

# Optional: Specify build steps if you were using a bundler like Webpack or esbuild
# [build]
# command = "npm run build" # Example build command
# upload.format = "service-worker" # Or "modules" depending on your script

# You might need to add account_id if wrangler can't infer it.
# Run `wrangler whoami` to find your Account ID.
# account_id = "1c4db339cf161e727379d041b5b7857d" 